# Generated by Django 2.1 on 2018-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseCode',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
