# Generated by Django 2.1.5 on 2019-02-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_questionpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='questions',
        ),
        migrations.DeleteModel(
            name='questionPaper',
        ),
    ]
