# Generated by Django 2.1.5 on 2019-03-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0016_auto_20190303_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
