# Generated by Django 2.1.5 on 2019-03-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0017_auto_20190303_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='course',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='questions',
        ),
        migrations.DeleteModel(
            name='questionPaper',
        ),
    ]
