# Generated by Django 2.1.5 on 2019-03-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0023_auto_20190306_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
