# Generated by Django 2.1.5 on 2019-03-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0024_auto_20190307_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='examhash',
            field=models.CharField(default='Sd', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
