# Generated by Django 2.1.5 on 2019-03-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0025_auto_20190307_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='examhash',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
