# Generated by Django 2.1.5 on 2019-03-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0026_auto_20190307_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
