# Generated by Django 2.1.5 on 2019-03-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0028_auto_20190314_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
