# Generated by Django 2.1.5 on 2019-03-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0029_auto_20190314_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
