# Generated by Django 2.1.5 on 2019-04-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0032_auto_20190401_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='launchStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
