# Generated by Django 2.1.5 on 2019-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0033_auto_20190421_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='examhash',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='question_of_course', to='Course.question'),
        ),
    ]
