# Generated by Django 2.1.5 on 2019-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0034_auto_20190421_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('binary', 'binary'), ('wh', 'wh')], default='binary', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='questions_of_paper', to='Course.question'),
        ),
    ]
