# Generated by Django 2.1.5 on 2019-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0035_auto_20190423_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionhash',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='questions_of_paper', to='Course.question'),
        ),
    ]
