# Generated by Django 2.1.5 on 2019-04-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0036_auto_20190423_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionhash',
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='questions_of_paper', to='Course.question'),
        ),
    ]
