# Generated by Django 2.1.5 on 2019-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0039_auto_20190423_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='intermediateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('questionHash', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='questions_of_paper', to='Course.question'),
        ),
    ]
