# Generated by Django 2.1 on 2018-08-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majordegree', models.CharField(max_length=64)),
                ('deptbelong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descipline', to='Home.department')),
            ],
        ),
        migrations.CreateModel(
            name='purePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('pureperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.purePerson')),
                ('idNum', models.CharField(max_length=8)),
                ('yrEmployed', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
            bases=('Home.pureperson',),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('pureperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.purePerson')),
                ('roll', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
            ],
            bases=('Home.pureperson',),
        ),
        migrations.AddField(
            model_name='pureperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='pureAdmin',
            fields=[
                ('faculty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.faculty')),
                ('adminusername', models.CharField(max_length=16)),
                ('adminpasscode', models.CharField(max_length=16)),
            ],
            bases=('Home.faculty',),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.faculty'),
        ),
    ]
