# Generated by Django 2.1 on 2018-10-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='pureperson_ptr',
        ),
        migrations.RemoveField(
            model_name='pureadmin',
            name='faculty_ptr',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
        migrations.DeleteModel(
            name='faculty',
        ),
        migrations.DeleteModel(
            name='pureAdmin',
        ),
    ]
