# Generated by Django 2.1 on 2018-10-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20181005_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='pureAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminusername', models.CharField(max_length=16)),
                ('adminpasscode', models.CharField(max_length=16)),
            ],
        ),
    ]
