# Generated by Django 2.1 on 2018-10-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_pureadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNum', models.CharField(max_length=8)),
                ('yrEmployed', models.IntegerField()),
                ('salary', models.FloatField()),
                ('pPerson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.purePerson')),
            ],
        ),
    ]
