# Generated by Django 2.1 on 2018-10-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20181005_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('pPerson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.purePerson')),
            ],
        ),
    ]
