# Generated by Django 2.1 on 2018-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='pureperson',
            name='type',
            field=models.CharField(choices=[('student', 'student'), ('faculty', 'faculty'), ('pureAdmin', 'pureAdmin')], default='student', max_length=20),
        ),
    ]
