# Generated by Django 2.1 on 2018-12-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_student_coursestaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty_access',
            field=models.BooleanField(default=False),
        ),
    ]
