# Generated by Django 2.1.5 on 2019-02-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_student_faculty_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='deptbelong',
        ),
        migrations.DeleteModel(
            name='major',
        ),
    ]
