# Generated by Django 2.1.5 on 2019-02-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20190207_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(default='xyz', max_length=64),
        ),
    ]
