# Generated by Django 2.1.5 on 2019-02-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_faculty_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(default='', max_length=64),
        ),
    ]
