# Generated by Django 2.1.5 on 2019-02-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20190207_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty_access',
        ),
    ]
