# Generated by Django 2.1.5 on 2019-02-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_remove_student_faculty_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='salary',
        ),
    ]
