# Generated by Django 2.1.5 on 2019-02-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_faculty_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='courses',
            field=models.ManyToManyField(related_name='course_faculties', to='Course.course'),
        ),
    ]
