# Generated by Django 2.1.5 on 2019-02-28 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20190227_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pureAdmin',
        ),
    ]
