# Generated by Django 2.1.5 on 2019-02-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_delete_pureadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='pureAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminusername', models.CharField(max_length=16)),
                ('adminpasscode', models.CharField(max_length=16)),
                ('pPerson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.purePerson')),
            ],
        ),
    ]
