# Generated by Django 2.1.5 on 2019-04-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0034_auto_20190421_1423'),
        ('Home', '0018_pureadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoreExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='Course.questionPaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='Home.student')),
            ],
        ),
    ]
