# Generated by Django 2.1.5 on 2019-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_scoreexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreexam',
            name='outof',
            field=models.IntegerField(default=0),
        ),
    ]
