# Generated by Django 2.1.5 on 2019-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_scoreexam_outof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreexam',
            name='outof',
            field=models.IntegerField(),
        ),
    ]
